FROM bitnami/python:3.12.5-debian-12-r0

ARG container_user=openg2p
ARG container_user_group=openg2p
ARG container_user_uid=1001
ARG container_user_gid=1001

RUN groupadd -g ${container_user_gid} ${container_user_group} \
  && useradd -mN -u ${container_user_uid} -G ${container_user_group} -s /bin/bash ${container_user}

RUN install_packages libpq-dev \
  && apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /app

ADD openg2p-g2p-bridge-models /app/openg2p-g2p-bridge-models
ADD openg2p-g2p-bridge-bank-connectors /app/openg2p-g2p-bridge-bank-connectors
ADD openg2p-g2p-bridge-celery-workers /app/openg2p-g2p-bridge-celery-workers
ADD openg2p-g2p-bridge-agency-allocator /app/openg2p-g2p-bridge-agency-allocator
ADD openg2p-g2p-bridge-warehouse-allocator /app/openg2p-g2p-bridge-warehouse-allocator
ADD openg2p-g2p-bridge-geo-resolver /app/openg2p-g2p-bridge-geo-resolver
ADD openg2p-g2p-bridge-notification-connectors /app/openg2p-g2p-bridge-notification-connectors

RUN mv /app/openg2p-g2p-bridge-celery-workers/main.py /app

RUN python3 -m pip install git+https://github.com/openg2p/openg2p-fastapi-common@1.1\#subdirectory=openg2p-fastapi-common  # to_be_removed_on_tag
RUN python3 -m pip install git+https://github.com/openg2p/openg2p-g2pconnect-common-lib@1.1\#subdirectory=openg2p-g2pconnect-common-lib # to_be_removed_on_tag
RUN python3 -m pip install git+https://github.com/openg2p/openg2p-g2pconnect-common-lib@1.1\#subdirectory=openg2p-g2pconnect-mapper-lib # to_be_removed_on_tag
RUN python3 -m pip install \
    -e /app/openg2p-g2p-bridge-models \
    -e /app/openg2p-g2p-bridge-bank-connectors \
    -e /app/openg2p-g2p-bridge-agency-allocator \
    -e /app/openg2p-g2p-bridge-warehouse-allocator \
    -e /app/openg2p-g2p-bridge-agency-allocator \
    -e /app/openg2p-g2p-bridge-geo-resolver \
    -e /app/openg2p-g2p-bridge-notification-connectors \
    -e /app/openg2p-g2p-bridge-celery-workers 


USER ${container_user}

CMD celery -A main.celery_app worker -Q g2p_bridge_celery_worker_tasks --loglevel=info
